development:
  adapter: mysql2
  database: feeder2app_development
  username: root
  password: root
  host: localhost
  port: 3306

test:
  adapter: mysql2
  database: feeder2app_test
  username: root
  password: root
  host: localhost
  port: 3306

production:
  adapter: mysql2
  database: feeder2app_production
  username: root
  password: root
  host: localhost
  port: 3306
